name: Deploy to Server

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - "frontend/**"
      - "docker-compose.yml"

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            # ورود به پوشه پروژه
            cd /home/user/jwt-auth-project

            # Pull آخرین تغییرات
            git pull origin main

            # متوقف کردن containerهای قبلی
            docker-compose down

            # Pull imageهای جدید
            docker-compose pull

            # Build و اجرا
            docker-compose up -d --build

            # پاک‌سازی
            docker system prune -af --volumes

            # نمایش وضعیت
            docker-compose ps

      - name: Health Check
        run: |
          sleep 30
          curl -f ${{ secrets.SERVER_HOST }}:8000 || exit 1
          curl -f ${{ secrets.SERVER_HOST }}:4200 || exit 1
